# Generated by Django 5.1.1 on 2024-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
